spring:
  application.name: comment-service
  profiles.active: local
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    serialization:
      write_dates_as_timestamps: false

  datasource:
    url: "jdbc:postgresql://localhost:5432/Comments"
    username: "postgres"
    password: "123456789"
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/main-changelog.yml

server:
  port: 8081
  servlet.context-path: /v1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
