spring:
  application.name: news-service
  profiles.active: dev
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    serialization:
      write_dates_as_timestamps: false

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            type: lucene
            directory.root: ./data/index

  liquibase:
    change-log: classpath:/db/changelog/main-changelog.yml

server:
  port: 8080
  servlet.context-path: /v1

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR

cache:
  type: LRU
  capacity: 10

feign:
  client:
    comment-service:
      name: comment-service
      url: http://comments-service:8080/v1/comments

---

spring:
  config:
    activate:
      on-profile: test

feign:
  client:
    comment-service:
      name: comment-service
      url: http://localhost:8080/v1/comments

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:postgresql://localhost:5433/News"
    username: "postgres"
    password: "123456789"
    driver-class-name: org.postgresql.Driver

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: "jdbc:postgresql://prod:5433/News"
    username: "prod_user"
    password: "prod_password"
    driver-class-name: org.postgresql.Driver
