version: "3.8"
services:
  news_db:
    image: 'postgres:15.3'
    container_name: news_db
    restart: always
    environment:
      - POSTGRES_DB=News
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
    ports:
      - '5433:5433'

  comments:
    image: 'news-service-image'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news
    depends_on:
      - news_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://news_db:5433/News
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8082:8082'